// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB91Lb8LH8jaPutw7tl-v4quxNlTa4apT4',
    appId: '1:1073622768697:web:6d6729eb2e3fa5842f41e8',
    messagingSenderId: '1073622768697',
    projectId: 'auth-test-9056c',
    authDomain: 'auth-test-9056c.firebaseapp.com',
    storageBucket: 'auth-test-9056c.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAX1GLqIAN13pxkoOOTdS0h-CwICMSFmY4',
    appId: '1:1073622768697:android:1ba0bb16aa627d9a2f41e8',
    messagingSenderId: '1073622768697',
    projectId: 'auth-test-9056c',
    storageBucket: 'auth-test-9056c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCZFAIMOzhMb7rs579ZHoeium4ognqRt4Q',
    appId: '1:1073622768697:ios:33dd9c9a9524e7ba2f41e8',
    messagingSenderId: '1073622768697',
    projectId: 'auth-test-9056c',
    storageBucket: 'auth-test-9056c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCZFAIMOzhMb7rs579ZHoeium4ognqRt4Q',
    appId: '1:1073622768697:ios:33dd9c9a9524e7ba2f41e8',
    messagingSenderId: '1073622768697',
    projectId: 'auth-test-9056c',
    storageBucket: 'auth-test-9056c.firebasestorage.app',
    iosBundleId: 'com.example.firebase',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB91Lb8LH8jaPutw7tl-v4quxNlTa4apT4',
    appId: '1:1073622768697:web:f06fd8ad64332baa2f41e8',
    messagingSenderId: '1073622768697',
    projectId: 'auth-test-9056c',
    authDomain: 'auth-test-9056c.firebaseapp.com',
    storageBucket: 'auth-test-9056c.firebasestorage.app',
  );
}
